version: '3.8'

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg14
    environment:
      POSTGRES_DB: iotdata
      POSTGRES_USER: iotuser
      POSTGRES_PASSWORD: iotpass
    ports:
      - "5432:5432"
    volumes:
      - timescaledb_data:/var/lib/postgresql/data

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana_data:/var/lib/grafana

  metabase:
    image: metabase/metabase:latest
    ports:
      - "3001:3000"
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: iotdata
      MB_DB_PORT: 5432
      MB_DB_USER: iotuser
      MB_DB_PASS: iotpass
      MB_DB_HOST: timescaledb

  superset:
    image: apache/superset:latest
    ports:
      - "8088:8088"
    environment:
      SUPERSET_SECRET_KEY: your_secret_key_here
    volumes:
      - superset_data:/app/superset_home

  data_generator:
    build: 
      context: ./data_generator
    environment:
      DB_HOST: timescaledb
      DB_NAME: iotdata
      DB_USER: iotuser
      DB_PASS: iotpass
    depends_on:
      - timescaledb

volumes:
  timescaledb_data:
  grafana_data:
  superset_data:
