version: '3.8'

services:
  timescaledb:
    build: 
      context: ./timescaledb
    environment:
      POSTGRES_DB: iotdata
      POSTGRES_USER: iotuser
      POSTGRES_PASSWORD: iotpass
    ports:
      - "5432:5432"
    volumes:
      - timescaledb_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U iotuser -d iotdata"]
      interval: 10s
      timeout: 5s
      retries: 5

  grafana:
    image: docker.io/grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana_data:/var/lib/grafana

  metabase:
    image: docker.io/metabase/metabase:latest
    ports:
      - "3001:3000"
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: iotdata
      MB_DB_PORT: 5432
      MB_DB_USER: iotuser
      MB_DB_PASS: iotpass
      MB_DB_HOST: timescaledb

  data_generator:
    build: 
      context: ./data_generator
    environment:
      DB_HOST: timescaledb
      DB_NAME: iotdata
      DB_USER: iotuser
      DB_PASS: iotpass
    depends_on:
      timescaledb:
        condition: service_healthy

volumes:
  timescaledb_data:
  grafana_data:
  superset_data:
